### ISSUE TITLE
Error when starting ./sitl.sh

### ISSUE THREAD

**Issue by laxnpander** [ykhedar/sim_docker#1]
Following instructions (except nvidia driver install) until ./sitl.sh:

Invalid <arg> tag: mavlink_sitl_gazebo
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
ROS path [2]=/home/root/src/Firmware
ROS path [3]=/home/root/src/Firmware/Tools/sitl_gazebo

**Comment by ykhedar** [comment]
It might be due to the gazebo sitl target not built. I have updated the README to include the instruction to be carried out during the first time to make this target. Essentially you  have to enter the image in bash mode by typing:
```bash
$ ./sitl.sh bash
```
and then make the target
```bash
$ cd home/root/src/Firmware/
$ make posix_sitl_default gazebo
```
and then after the target is built, it will launch the simulation but it will be default simulation and we don't want this. So quit the docker and then again run the docker in normal mode by typing
```bash
$ ./sitl.sh
```

**Comment by laxnpander** [comment]
That solved this issue, thanks!
